# _config.yml

title: "Jekyll Actions Demo"

baseurl: "/jekyll-ga-test" # the subpath of your site, e.g. /blog
url: "https://geotheory.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-basically-basic
plugins:
  - jekyll-feed
permalink: /posts/:year-:month-:day-:title/
safe: false
